modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/MORIMORI0317/BEStyleWither/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "bestylewither"
version = "${version}"
displayName = "BE Style Wither"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/be-style-wither"
authors = "MORIMORI0317"
description = '''
This mod brings the behavior of Wither closer to Bedrock Edition.
The ikisugi wither mod...
'''
logoFile = "icon.png"
[modproperties.bestylewither]
catalogueImageIcon = "icon.png"